modLoader = "javafml"
loaderVersion = "[43,)"
license = "GPL-3.0"

[[mods]]
modId = "bounced"
version = "${version}"
displayName = "Bounced"
displayURL = "https://github.com/KrLite/Bounced"
authors = "KrLite, TexTrue"
description = '''
Such A Vibrant Title!
'''
logoFile = "icon.png"

[[dependencies.bounced]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bounced]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.19.2]"
ordering = "NONE"
side = "BOTH"

[[dependencies.bounced]]
modId = "architectury"
mandatory = true
versionRange = "[6,)"
ordering = "AFTER"
side = "BOTH"