class Display {
    String name
    String loader
    String version
}

plugins {
    id "maven-publish"
    alias(libs.plugins.architectury.loom)
    alias(libs.plugins.modpublisher)
}

Display display = new Display()

group = libs.versions.maven.group.get()
version = "${libs.versions.mod.get()}-${libs.versions.loader.get()}${libs.versions.minecraft.get()}"
base.archivesName = "${libs.versions.archives.name.get()}"

display.name = libs.versions.display.name.get()
display.loader = libs.versions.display.loader.get()
display.version = libs.versions.display.version.get()

repositories {
    mavenCentral()
    maven { url = "https://jitpack.io" }
    maven { url = "https://api.modrinth.com/maven" }
    maven { url = "https://maven.neoforged.net/releases/" }
}

dependencies {
    minecraft(libs.minecraft)
    mappings(libs.yarn) { artifact { classifier = "v2" } }
    neoForge(libs.neoforge)

    modCompileOnly(libs.splasher)
}

processResources {
    inputs.property "version", project.version

    filesMatching("META-INF/mods.toml") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
    options.release = 17
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17

    withSourcesJar()
}

jar {
    from("LICENSE")
}

// configure the maven publication
publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }

    repositories {
    }
}

publisher {
    apiKeys {
        modrinth(System.getenv("MODRINTH_TOKEN"))
        curseforge(System.getenv("CURSEFORGE_TOKEN"))
    }

    setModrinthID(libs.versions.id.modrinth)
    setCurseID(libs.versions.id.curseforge)

    setVersionType("release")
    setVersion(project.version.toString())
    setGameVersions("1.20.3", "1.20.4")
    setLoaders("neoforge")

    setDisplayName("${display.name} ${libs.versions.mod.get()} for ${display.loader} ${display.version}")

    setArtifact(remapJar)
    addAdditionalFile(remapSourcesJar)

    setChangelog(file("CHANGELOG.md"))
}
