[versions]
maven-group = "band.kessokuteatime"
archives-name = "bounced"
mod = "4.1.0"
loader = "fabric"

minecraft = "1.20.4"
yarn = "1.20.4+build.3"
fabric-loader = "0.15.9"
fabric-api = "0.96.11+1.20.4"
fabric-loom = "1.6-SNAPSHOT"
modpublisher = "2.1.0"

splasher = "6.0.0-mc1.20"

#id
id-modrinth = "2mlOZXZr"
id-curseforge = "844458"

# display
display-name = "Bounced"
display-loader = "Fabric"
display-version = "1.20.4"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
yarn = { group = "net.fabricmc", name = "yarn", version.ref = "yarn" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }

splasher = { group = "maven.modrinth", name = "splasher", version.ref = "splasher" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
modpublisher = { id = "com.hypherionmc.modutils.modpublisher", version.ref = "modpublisher" }

[bundles]
fabric = ["fabric-loader", "fabric-api"]
