[versions]
maven-group = "band.kessokuteatime"
archives-name = "bounced"
mod = "4.1.0"
loader = "forge"

minecraft = "1.20.1"
yarn = "1.20.1+build.10"
forge = "1.20.1-47.2.21"
architectury-loom = "1.5-SNAPSHOT"
modpublisher = "2.1.0"

splasher = "6.0.3-mc1.20-forge"

# id
id-modrinth = "2mlOZXZr"
id-curseforge = "844458"

# display
display-name = "Bounced"
display-loader = "Forge"
display-version = "1.20~1.20.1"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
yarn = { group = "net.fabricmc", name = "yarn", version.ref = "yarn" }
forge = { group = "net.minecraftforge", name = "forge", version.ref = "forge" }

splasher = { group = "maven.modrinth", name = "splasher", version.ref = "splasher" }

[plugins]
architectury-loom = { id = "dev.architectury.loom", version.ref = "architectury-loom" }
modpublisher = { id = "com.hypherionmc.modutils.modpublisher", version.ref = "modpublisher" }
